default:
  site_name:
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#CCC'
  brand: 'shared/default_brand'
  home_banner: 'cove_home_banner.jpeg'
public:
  site_name: Public
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#CCC'
  home_banner: 'cove_home_banner.jpeg'
studio:
  site_name: COVE
  welcome_message: 'Sign in above, or via <a href="http://navsa.org">NAVSA</a>'
  welcome_blurb: 'COVE Studio is the annotation and peer review workbench for COVE edition documents, which you can view on the <a href="http://dev-rc-distro.pantheonsite.io">COVE editions</a> website.'
  site_color: '#279eb2'
  home_banner: 'cove_home_banner.jpeg'
  brand: 'shared/cove_brand'
navsaconference:
  site_name: NAVSA Conference
  welcome_message: 'Welcome to Conference COVE Studio'
  welcome_blurb: 'COVE Studio is a web application that supports close reading and collaborative interpretation of online documents.'
  site_color: '#671900'
  home_banner: 'navsa_2020.png'
  brand: 'shared/navsa_conference_brand'
bavs-staging:
  site_name: BAVS
  welcome_message: 'Sign in via <a href="https://bavs.ac.uk/">BAVS</a>'
  welcome_blurb: 'COVE Studio for BAVS is the annotation and peer review workbench for BAVS.'
  site_color: '#279eb2'
  brand: 'shared/bavs_brand'
bavs:
  site_name: BAVS
  welcome_message: 'Sign in via <a href="https://bavs.ac.uk/">BAVS</a>'
  welcome_blurb: 'COVE Studio for BAVS is the annotation and peer review workbench for BAVS.'
  site_color: '#279eb2'
  brand: 'shared/bavs_brand'
