default:
  site_name:
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#CCC'
  brand: 'shared/default_brand'
  home_banner: 'cove_home_banner.jpg'
public:
  site_name: Public
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#CCC'
  home_banner: 'cove_home_banner.jpg'
studio.covecollective.org:
  site_name: COVE
  oauth_provider: NAVSA
  welcome_message: 'Sign in above, or via <a href="http://navsa.org">NAVSA</a>'
  welcome_blurb: 'COVE Studio is the annotation and peer review workbench for COVE edition documents, which you can view on the <a href="http://dev-rc-distro.pantheonsite.io">COVE editions</a> website.'
  site_color: '#279eb2'
  home_banner: 'cove_home_banner.jpg'
  brand: 'shared/cove_brand'
staging.covecollective.org:
  site_name: COVE Staging
  oauth_provider: NAVSA
  welcome_message: 'Sign in above, or via <a href="http://navsa.org">NAVSA</a>'
  welcome_blurb: 'COVE Studio is the annotation and peer review workbench for COVE edition documents, which you can view on the <a href="http://dev-rc-distro.pantheonsite.io">COVE editions</a> website.'
  site_color: '#279eb2'
  home_banner: 'cove_home_banner.jpg'
  brand: 'shared/cove_brand'
navsaconference-staging.covecollective.org:
  site_name: Event 2024 - Staging
  welcome_message: 'Welcome to COVE Conferences'
  welcome_blurb: 'COVE Studio is a web application that supports close reading and collaborative interpretation of online documents.'
  site_color: '#ffe77a'
  banner_color: '#2C5F2D'
  home_banner: 'cove_conferences_banner.jpg'
  brand: 'shared/navsa_conference_brand'
navsaconference.covecollective.org:
  site_name: Event 2024
  welcome_message: 'Welcome to COVE Conferences'
  welcome_blurb: 'COVE Studio is a web application that supports close reading and collaborative interpretation of online documents.'
  site_color: '#ffe77a'
  banner_color: '#2C5F2D'
  home_banner: 'cove_conferences_banner.jpg'
  brand: 'shared/navsa_conference_brand'
bavs-staging.covecollective.org:
  site_name: BAVS
  oauth_provider: BAVS
  welcome_message: 'Sign in via <a href="https://bavs.ac.uk/">BAVS</a>'
  welcome_blurb: 'Welcome the BAVS imprint of COVE, The Central Online Victorian Educator. COVE is a scholar-driven open-access platform that publishes peer-reviewed Victorian material. It is maintained and supported by NAVSA, BAVSA, AVSA and a number of independent institutions, and aims to make access to diverse scholarly editions and Victorian voices more widely available. Although all peer-reviewed material is open access, we charge a modest amount for use of our tools (for more information, see COVE Tools and Anthology Builder below). To facilitate its use throughout the COVID-19 pandemic, BAVS are offering some funds to support student access to develop specific projects. For more information on this, and for any other BAVS-specific issues regarding COVE use, please contact <a href="mailto:Joanna.taylor@manchester.ac.uk">Joanna Taylor</a>. If you are interested in getting involved with COVE, please contact General Editor <a href="mailto:felluga@purdue.edu">Dino Franco Felluga</a>.'
  site_color: '#279eb2'
  home_banner: 'bavs-banner.jpg'
  brand: 'shared/bavs_brand'
bavs.covecollective.org:
  site_name: BAVS
  oauth_provider: BAVS
  welcome_message: 'Sign in via <a href="https://bavs.ac.uk/">BAVS</a>'
  welcome_blurb: 'Welcome the BAVS imprint of COVE, The Central Online Victorian Educator. COVE is a scholar-driven open-access platform that publishes peer-reviewed Victorian material. It is maintained and supported by NAVSA, BAVSA, AVSA and a number of independent institutions, and aims to make access to diverse scholarly editions and Victorian voices more widely available. Although all peer-reviewed material is open access, we charge a modest amount for use of our tools (for more information, see COVE Tools and Anthology Builder below). To facilitate its use throughout the COVID-19 pandemic, BAVS are offering some funds to support student access to develop specific projects. For more information on this, and for any other BAVS-specific issues regarding COVE use, please contact <a href="mailto:Joanna.taylor@manchester.ac.uk">Joanna Taylor</a>. If you are interested in getting involved with COVE, please contact General Editor <a href="mailto:felluga@purdue.edu">Dino Franco Felluga</a>.'
  site_color: '#279eb2'
  home_banner: 'bavs-banner.jpg'
  brand: 'shared/bavs_brand'
purdue.covecollective.org:
  site_name: Purdue
  welcome_message: 'Welcome to COVE Studio for Purdue'
  welcome_blurb: 'Welcome to COVE Studio for Purdue'
  site_color: '#CFB53B'
  home_banner: 'purdue_banner.jpg'
  brand: 'shared/purdue_brand'
  saml_provider: 'purdue.edu'
  saml_metadata: '/saml/purdue_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
purdue-staging.covecollective.org:
  site_name: Purdue
  welcome_message: 'Welcome to COVE Studio for Purdue'
  welcome_blurb: 'Welcome to COVE Studio for Purdue'
  site_color: '#CFB53B'
  home_banner: 'purdue_banner.jpg'
  brand: 'shared/purdue_brand'
  saml_provider: 'purdue.edu'
  saml_metadata: '/saml/purdue_staging_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
princeton-staging.covecollective.org:
  site_name: Princeton Staging
  welcome_message: 'Welcome to COVE Studio for Princeton'
  welcome_blurb: 'Welcome to COVE Studio for Princeton'
  site_color: '#e77500'
  home_banner: 'princeton_banner.jpg'
  brand: 'shared/princeton_brand'
  saml_provider: 'princeton.edu'
  saml_metadata: '/saml/princeton_staging_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
princeton.covecollective.org:
  site_name: Princeton
  welcome_message: 'Welcome to COVE Studio for Princeton'
  welcome_blurb: 'Welcome to COVE Studio for Princeton'
  site_color: '#e77500'
  home_banner: 'princeton_banner.jpg'
  brand: 'shared/princeton_brand'
  saml_provider: 'princeton.edu'
  saml_metadata: '/saml/princeton_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
nassr-staging.covecollective.org:
  site_name: NASSR Staging
  welcome_message: 'Welcome to COVE Studio for NASSR'
  welcome_blurb: 'Welcome to COVE Studio for NASSR'
  site_color: '#5f7457'
  home_banner: 'nassr_banner.jpg'
  brand: 'shared/nassr_brand'
nassr.covecollective.org:
  site_name: NASSR
  welcome_message: 'Welcome to COVE Studio for NASSR'
  welcome_blurb: 'Welcome to COVE Studio for NASSR'
  site_color: '#5f7457'
  home_banner: 'nassr_banner.jpg'
  brand: 'shared/nassr_brand'
ua-staging.covecollective.org:
  site_name: U of Alabama Staging
  welcome_message: 'Welcome to COVE Studio for the University of Alabama'
  welcome_blurb: 'Welcome to COVE Studio for the University of Alabama'
  site_color: '#9e1b32'
  home_banner: 'alabama_banner.jpg'
  brand: 'shared/alabama_brand'
  saml_provider: 'ua.edu'
  saml_metadata: '/saml/ua_staging_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
ua.covecollective.org:
  site_name: U of Alabama
  welcome_message: 'Welcome to COVE Studio for the University of Alabama'
  welcome_blurb: 'Welcome to COVE Studio for the University of Alabama'
  site_color: '#9e1b32'
  home_banner: 'alabama_banner.jpg'
  brand: 'shared/alabama_brand'
  saml_provider: 'ua.edu'
  saml_metadata: '/saml/ua_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
uchicago-staging.covecollective.org:
  site_name: University of Chicago Staging
  welcome_message: 'Welcome to COVE Studio for the University of Chicago'
  welcome_blurb: 'Welcome to COVE Studio for the University of Chicago'
  site_color: '#800000'
  home_banner: 'chicago_banner.jpg'
  brand: 'shared/chicago_brand'
  saml_provider: 'uchicago.edu'
  saml_metadata: '/saml/uchicago_staging_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
uchicago.covecollective.org:
  site_name: University of Chicago
  welcome_message: 'Welcome to COVE Studio for the University of Chicago'
  welcome_blurb: 'Welcome to COVE Studio for the University of Chicago'
  site_color: '#800000'
  home_banner: 'chicago_banner.jpg'
  brand: 'shared/chicago_brand'
  saml_provider: 'uchicago.edu'
  saml_metadata: '/saml/uchicago_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
ryerson-staging.covecollective.org:
  site_name: Ryerson University Staging
  welcome_message: 'Welcome to COVE Studio for Ryerson University'
  welcome_blurb: 'Welcome to COVE Studio for Ryerson University'
  site_color: '#00a9ef'
  home_banner: 'ryerson_banner.jpg'
  brand: 'shared/ryerson_brand'
  saml_provider: 'ryerson.ca'
  saml_metadata: '/saml/ryerson_staging_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
ryerson.covecollective.org:
  site_name: Ryerson University
  welcome_message: 'Welcome to COVE Studio for Ryerson University'
  welcome_blurb: 'Welcome to COVE Studio for Ryerson University'
  site_color: '#00a9ef'
  home_banner: 'ryerson_banner.jpg'
  brand: 'shared/ryerson_brand'
  saml_provider: 'ryerson.ca'
  saml_metadata: '/saml/ryerson_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
colum-staging.covecollective.org:
  site_name: Columbia College Staging
  welcome_message: 'Welcome to COVE Studio for Columbia College Chicago'
  welcome_blurb: 'Welcome to COVE Studio for Columbia College Chicago'
  site_color: '#048194'
  home_banner: 'columbia_college_banner.jpg'
  brand: 'shared/columbia_college_brand'
  saml_provider: 'colum.edu'
  saml_metadata: '/saml/colum_staging_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
colum.covecollective.org:
  site_name: Columbia College
  welcome_message: 'Welcome to COVE Studio for Columbia College Chicago'
  welcome_blurb: 'Welcome to COVE Studio for Columbia College Chicago'
  site_color: '#048194'
  home_banner: 'columbia_college_banner.jpg'
  brand: 'shared/columbia_college_brand'
  saml_provider: 'colum.edu'
  saml_metadata: '/saml/colum_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
unl-staging.covecollective.org:
  site_name: U of Nebraska-Lincoln Staging
  welcome_message: 'Welcome to COVE Studio for the University of Nebraska - Lincoln'
  welcome_blurb: 'Welcome to COVE Studio for the University of Nebraska - Lincoln'
  site_color: '#d00000'
  home_banner: 'unl_banner.jpg'
  brand: 'shared/unl_brand.html.erb'
  saml_provider: 'unl.edu'
  saml_metadata: '/saml/unl_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
unl.covecollective.org:
  site_name: UNL
  welcome_message: 'Welcome to COVE Studio for the University of Nebraska - Lincoln'
  welcome_blurb: 'Welcome to COVE Studio for the University of Nebraska - Lincoln'
  site_color: '#d00000'
  home_banner: 'unl_banner.jpg'
  brand: 'shared/unl_brand.html.erb'
  saml_provider: 'unl.edu'
  saml_metadata: '/saml/unl_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
odu-staging.covecollective.org:
  site_name: Old Dominion U - Staging
  welcome_message: 'Welcome to COVE Studio for Old Dominion University'
  welcome_blurb: 'Welcome to COVE Studio for Old Dominion University'
  site_color: '#ACAAB4'
  home_banner: 'odu_banner.jpg'
  brand: 'shared/odu_brand.html.erb'
  saml_provider: 'odu.edu'
  saml_metadata: '/saml/odu_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
odu.covecollective.org:
  site_name: Old Dominion U
  welcome_message: 'Welcome to COVE Studio for Old Dominion University'
  welcome_blurb: 'Welcome to COVE Studio for Old Dominion University'
  site_color: '#ACAAB4'
  home_banner: 'odu_banner.jpg'
  brand: 'shared/odu_brand.html.erb'
  saml_provider: 'odu.edu'
  saml_metadata: '/saml/odu_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
macerata-staging.covecollective.org:
  site_name: U di Macerata - Staging
  welcome_message: 'Welcome to COVE Studio for Università di Macerata'
  welcome_blurb: 'Welcome to COVE Studio for Università di Macerata'
  site_color: '#957375'
  home_banner: 'macerata_banner.png'
  brand: 'shared/macerata_brand.html.erb'
  saml_metadata: '/saml/macerata_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
macerata.covecollective.org:
  site_name: U di Macerata
  welcome_message: 'Welcome to COVE Studio for Università di Macerata'
  welcome_blurb: 'Welcome to COVE Studio for Università di Macerata'
  site_color: '#957375'
  home_banner: 'macerata_banner.png'
  brand: 'shared/macerata_brand.html.erb'
  saml_metadata: '/saml/macerata_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
coastal-staging.covecollective.org:
  site_name: Coastal Carolina - Staging
  welcome_message: 'Welcome to COVE Studio for Coastal Carolina University'
  welcome_blurb: 'Welcome to COVE Studio for Coastal Carolina University'
  site_color: '#006F71'
  home_banner: 'coastal_banner.jpg'
  brand: 'shared/coastal_brand'
  saml_metadata: '/saml/coastal_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
coastal.covecollective.org:
  site_name: Coastal Carolina
  welcome_message: 'Welcome to COVE Studio for Coastal Carolina University'
  welcome_blurb: 'Welcome to COVE Studio for Coastal Carolina University'
  site_color: '#006F71'
  home_banner: 'coastal_banner.jpg'
  brand: 'shared/coastal_brand'
  saml_metadata: '/saml/coastal_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
psu-staging.covecollective.org:
  site_name: Penn State - Staging
  welcome_message: 'Welcome to COVE Studio for Penn State'
  welcome_blurb: 'Welcome to COVE Studio for Penn State'
  site_color: '#ffffff'
  home_banner: 'psu_banner.png'
  brand: 'shared/psu_brand'
  saml_metadata: '/saml/psu_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
psu.covecollective.org:
  site_name: Penn State
  welcome_message: 'Welcome to COVE Studio for Penn State'
  welcome_blurb: 'Welcome to COVE Studio for Penn State'
  site_color: '#ffffff'
  home_banner: 'psu_banner.png'
  brand: 'shared/psu_brand'
  saml_metadata: '/saml/psu_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'